---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mail-relay-secret
  namespace: mail-relay
spec:
  encryptedData:
    password: AgBKJJi2wLkSa0vRN6Ml0KuKKywULZtZwg4iNiuI2iubAxF87ePznDVvaRIlpbhUTN4x3npPMEk6umZ6NyL1vzNGEcTtNxf+0fA12bRsHyA1aYOz1jxJd9jCU5TLbH5LExODihUbkaQReyZajT4Zb0QgUYEWy6LJKSabNWNjFhfhKdJMBIQI+wneasPxUCQgJ+UFjh/UByIUcCtDPWCXu1eFYl8u4kRTEGB0f3hz345GcuFHNw37vDzkDbt5qjxUDydoRvz/IX91Yyi1oNMdtxQ7Z0MXC7S5dx4wUFhtBwNZmqlwfG7Sbe4WQn7SPZAhi7oImOcX5BcXRfu4D7PXcsdYDzo3PQTla5T5YtffFqvN9/Ooutrce9smvQeXtQOf0FJ1cln/DZ0sIvR9pb4s1Mkl4XMKAjdq1lx111cTqSuOQAmFOCDiKiObXhdoefiwTYmQfqOYN35PsGQ0qH03SJTvy3Tk+EM2e2J3mfDRiLQhvdta7avSKgP8zv/Cns102PjRaUWcx3v357Id6vhpGHkxPV3a8av/fqu01TQjltSNn10oiwm9gi9OOfQE5Z/aw99vtmOu1Ha3TJCwqrSh6eWtXr5yHy/zsNxvYIKTc+sA1qPGD9wOv4XptWscwD7W8rRFxwt2+TkAESi5xkM/3i6E+zRpBt/GlsvdewF/6IMyGHddLw3zbgeoPCyeTk2c/4vAwDy1P4HCufQ=
    username: AgCDysW/GRa0f699CKG36jHBTz8/aoK9HWW/kiQO3KV9AjjqsS3q7CcDgZsmrz6r3s1Og66ux3AsinKfyPeNv1Bqz0yzEpYBAtDkGSow/5y3biDzvSq/77hP03vmirPlMwOoCFEWwIZaSJQwPx64XtA84i3GDr9q7fusGfLU+/tqpIUxOKBJ8i260v3kNmqXmmjGpzLbUZAMIHpNwkWrBctj+2BiT0KsJ4peV3Cu4ewjOi3il6DUSFrBZk28r9oVUsP+ySVHhuvPMgq0GPLQJ4MbDuVqvELWGEpkzt9SFIUB9m0VNWDdHZEXV0YWVPGxDRXmT+7elOZ8OzvTr192mCQnzAmvmtFO5DDjmKMH7C8o2btk1gbXiMt5Scaxb29Ne9QymFrysTU4CKz5pM/wjdSDlVbRh2h4UQCcZd48L1f0hqBtPID6E5nusB0MpHSC2Fv1rsHdbOA75bNYYTrUuTXE77qt7DCuhZs5MuhCFgjtyK+KZfZNxpUKqiRLPnClNL8vzf9xonzzOWGCH1ziV1+ag6cUJY2FM13QYtt+YFWp+0qI3EK/NRrYYQWjlVwYhOFhhLix71TrpCBBOD5yjQufC35kWS4kygHHxLGpmyXv/6ExkKyfpmPzyj0wZrn5PiUEXczODyQQ+fSLcF51r1sMVJJpqRXFKt2TpiHU9tWAn0wQOSus+kgMBZeYxty9mXq+BS2rtUPOmNldAARRfir7Toq7KzBonNlvhltdnhyTUUcDOmk=
  template:
    metadata:
      creationTimestamp: null
      name: mail-relay-secret
      namespace: mail-relay
