---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mail-relay-secret
  namespace: mail-relay
spec:
  encryptedData:
    password: AgCli5wqaKivmwa3F0LT0gsQSNEZE08OBKIYeE7sAaanvNzgTIjOG5Ctl5ZvJo46Ji+i+N/Mh+dU0h3+wilUKo3SzBc+m4aRRlYJPhOvkr1bCkRnp+OOfwlSKS4AgrYKsp47G+knSbj4HtB/d+KKo424L5MaqN25s7w/GqpS4NzFCakEd9EA3o75NE8pWtEcPmaSBZnzV8T0CCMTy5BsUAmsl3B1VCtjsHC8tXjoITjBoMrqXvYfYI+bfzsIR8o1QLa0oYbXxsrcWGsTTD/ZCkEcabu+AFahMMQM+O10Iwkwtav4RvvufJBwPAMfpI0IiUpQz/4InZfkp7GXiWAnu0nEKh4zMor/BMhdF0F449KISalswpXv8EGEP1gcNaSnfIQ3a7zN0V/595BH2ZrPFm8jGfLuZ0SfsaiEtR4I9WeIj934knwfzMiOJvPdfI/HCTlbraLIcR9UuMe1fvS6hSh55qxCqD3Lm6a4KJctaDkVSSRolycJtRFS52KRZQ+P58Mrz04heNwCRQ7fECIH/14Eml45VWZfrcknVGAeowR8Hq1QCadCa5lA0r5UdAC8tIMM08UThFVydDal6NyYOYGNCfQrkQKOmyPU39Xt6Ca/OFdnD5JJAO6gRyDLLLHhw3CUZXudIvpkVuhwfXglSD9wtjw7eJzGpHh0zCQHx90ShZ1jMvakGsRdHmdthg5MmTY+dtCEm5Y70qQ=
    username: AgCb4M9CLUX8O+WUZQQEI4hz7IDer7lR4M2nU/sUpXY/Zr8U7QNJaFSxE0xarz8b8ge+z3ggxmHqqCDaCGpj4NdoiKbqkPhqDMiHwICZ3J9q3pOhF6sCP/ztnh3ulKoAe35u+SEZ4/+zyYOax6VWv7l11wjXWbXX4+QtYi7WeuET1eqGl/S4/nzB23qnmVb22tkYKTCtyR9iztjon2OrnyyS5aAZZnbkneGT+HtIR6bcnAy1M0AViXLN26S67c/ZKeS5uOuSPs5kXB5g2RSwr9L66HJmBE+3u1lA2yz+/7gCxGvDu7opbHpVUiVxCXhfMRmWgl7tEsIEC0UmEiQS44KGzgigXCizbtiEbAwAgkNJM5NU2SyA4YdBpQh16/tGkF32DuMQ/EM/DCqnFcRZB6/oBZHttXopUN1iDsd0cC+GgpMnVYxV9yWCHl6/k8dIuect3/vZdWKHbejsXDVYFTQSpDl1nGmzgYsP7K0GWwk4eltyNw8TzNhrqJ9fX4isWnnI260av35AX1if8XiRg1bGICdEWyP5EAmDlNvPBsNdboMer4ph2ctkK6jgpk2X11v4RCP7HJi8kq8ZHr+KyfsRJ5rlRE3GqOsfyrReFDBGqM4WhRJT9eHLdxBZmt+CspOCCm5b325EvY8ojehTysgcbeVLrQc0ZJh2uGxGFqZRefy0nqHekgHrmvw0vJxTfBzd8tN4EfI41i6uKvSLQyvuUqHCA2oP2LzuvwM9uoItCtpcAt0=
  template:
    metadata:
      creationTimestamp: null
      name: mail-relay-secret
      namespace: mail-relay
