apiVersion: v1
kind: Service
metadata:
  name: mail-relay
  namespace: mail-relay
  labels:
    app: mail-relay
spec:
  selector:
    app: mail-relay
  ports:
    - name: submission
      port: 587
      targetPort: 587