---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: private-key-verifier
  namespace: billing
spec:
  encryptedData:
    PRIVATE_KEY_BASE64: AgBXmAB4dhKfYkfipkzubxMK4HTH1G/yWb7K1ywsKZcitmK1lzln42+DzHjBrWGR8RlBY5hBLgW0mTzgJxHOhX4wIz0qOtJSLwF2U0/N4vDc/yym9KmKx6/Jbruv+RQfX9EcCI4WA7ZABLg06eY+NgUL+hhMTpQEfB/LfEb2nnJMJPQaYeELLw1h4+qET5R5KjkUx6lBQ9VSTlmC+myLmJSurL1PsvoHzKDGtM6+ci0syhBhAL94S8viyT8B3tl0k1kZ+EUlqPjeFmYWRvkFF72/V04YdMyano9NvzaxJhrY5aAEALcV1TdpF0yEUWSIewwN/xvDDHAAFiB8iV3+9r53rKAvu2cZhu7rPwEFCln8RYf00iCWS/pEKO3vsGnxWP5x6kRmWLzMFxpXbAXJfy8Kqj1q1j4jkUBCvhHZ0jeL4+yqIPW3Ja+0sZzpSVP1ueV5xuir6oXA7njyvzo6kLYTM24m+cReV6RZCbj407ggp26j+YlbF04cqHK3D0/OAXCgyJ3UuJS24sATX9PKjrUppodl11qcg/SFwqOyPq6uBOBmQLVQBMMJUivXBj4MteueRo56lNTR25c15ZQCmZU7TpAqdIRnUQPBW9rHQrWwv1skd/FeGUpt9OTyNnCoou3/YG+1bGHDRCUdJ4/yIuT3bvoVRLc6xPeUABWr0mbI6zul6P+SCasrS28hef5lwUQ0An0lRhuSkMzOSGw1lcAByGipl/XTwcrJTTvu6nQsHnkGjxNfKfs1G0/rbQ==
  template:
    metadata:
      creationTimestamp: null
      name: private-key-verifier
      namespace: billing
