cert-manager:
  installCRDs: true
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  cainjector:
    resources:
      requests:
        cpu: 10m
        memory: 96Mi
      limits:
        cpu: 100m
        memory: 192Mi
  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
