{
 "title": "Standard Cluster Monitoring",
 "description": "Standard Kubernetes/OpenShift cluster monitoring dashboard (needs Prometheus recording rules)",
 "tags": [
  "kubernetes",
  "openshift",
  "cluster",
  "recording-rules",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "noderole",
    "label": "Node Role",
    "query": {
     "query": "label_values(instance:kube_node_role,role)"
    }
   },
   { "name": "sparenodesfactor", "label": "Spare Nodes", "query": "0, 1, 2, 3" },
   { "name": "nodecpumemreserve", "label": "Node CPU/Mem Reserve", "query": "0, 0.1, 0.2, 0.25, 0.333, 0.5" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition!=\"Ready\", status!=\"false\"})\n+\nsum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Failures (all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "sum by (condition) (kube_node_status_condition{condition!=\"Ready\", condition!=\"EtcdIsVoter\", status!=\"false\"})",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable)",
     "legendFormat": "Unschedulable"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "targets": [
    { "expr": "sum(kube_node_info)", "legendFormat": "total" },
    {
     "expr": "sum by (role) (instance:kube_node_role)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Unschedulable Nodes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (kube_node_spec_unschedulable * on(node) group_left() kube_node_role{role=~\"$noderole\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Nodes with unavailable Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (kube_node_status_condition{condition=\"NetworkUnavailable\", status!=\"false\"} * on(node) group_left() kube_node_role{role=~\"$noderole\"}) or vector(0)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Kubernetes Operation Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(node, operation_type) (rate(kubelet_runtime_operations_errors_total{cluster=\"\",job=\"kubelet\", metrics_path=\"/metrics\"}[5m]) * on(node) group_left() kube_node_role{role=~\"$noderole\"}) or vector(0)",
     "legendFormat": "{{node}}/{{operation_type}}"
    }
   ]
  },
  {
   "title": "Cores Used (from capacity)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\n(\n  sum(kube_node_status_capacity:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_capacity:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Cores Used Top Node",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,\n  100\n  /\n  (sum by (node) (kube_node_status_capacity:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve))\n  *\n  sum by (node) (node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})\n)"
    }
   ]
  },
  {
   "title": "CPU Cores Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "sum by (node) (node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Used (form capacity)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\n(\n  sum(kube_node_status_capacity:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_capacity:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(node_memory_MemUsed_bytes:sum{role=~\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Memory  Used Top Node",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,\n  100\n  /\n  (sum by (node) (kube_node_status_capacity:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve))\n  *\n  sum by (node) (node_memory_MemUsed_bytes:sum{role=~\"$noderole\"})\n)"
    }
   ]
  },
  {
   "title": "Memory usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (node_memory_MemUsed_bytes:sum{role=~\"$noderole\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_disk_read_bytes_total:sum_rate5m{role=~\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_disk_written_bytes_total:sum_rate5m{role=~\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Disk Read & Write by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (node) (node_disk_read_bytes_total:sum_rate5m{role=~\"$noderole\"})",
     "legendFormat": "(read) {{node}}"
    },
    {
     "expr": "sum by (node) (node_disk_written_bytes_total:sum_rate5m{role=~\"$noderole\"}) * -1",
     "legendFormat": " (write) {{node}}"
    }
   ]
  },
  {
   "title": "Network Receive",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_network_receive_bytes_total:sum_rate5m{role=~\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_network_transmit_bytes_total:sum_rate5m{role=~\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Network Bandwidth (receive & transmit) by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total:sum_rate5m{role=~\"$noderole\"}",
     "legendFormat": "(receive) {{node}}"
    },
    {
     "expr": "node_network_transmit_bytes_total:sum_rate5m{role=~\"$noderole\"} * -1",
     "legendFormat": "(transmit) {{node}}"
    }
   ]
  },
  {
   "title": "Capacity Management - Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 22, "x": 0, "y": 2 },
     "options": {
      "content": "- CPU / Memory capacity = total hardware resources\n- CPU / Memory allocatable (brutto) = total allocatable  \n- CPU / Memory allocatable (netto) = total allocatable - cpu/mem reserve - spare nodes  \n  -> All requested, used and limits values are calculated with the allocatable (netto) values"
     }
    },
    {
     "title": "Nodes ($noderole)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(instance:kube_node_role{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Available (requestable)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n-\nsum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n-\nsum(kube_pod_container_resource_requests:cpu:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Available (for usage)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n-\nsum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n-\nsum(node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores (capacity)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity:cpu:sum{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores (brutto)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores (netto)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n-\nsum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor"
      }
     ]
    },
    {
     "title": "Mem Available (requestable)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n-\nsum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n-\nsum(kube_pod_container_resource_requests:memory:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Mem Available (for usage)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n-\nsum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n-\nsum(node_memory_MemUsed_bytes:sum{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory (capacity)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity:memory:sum{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory (brutto)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory (netto)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n-\nsum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor"
      }
     ]
    },
    {
     "title": "Cores Requested (from netto)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(kube_pod_container_resource_requests:cpu:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Used (from netto)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Used (from requested)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:cpu:running{role=~\"$noderole\"})\n*\nsum(container_cpu_usage_seconds_total:sum_rate5m{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Limits (from netto)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(kube_pod_container_resource_limits:cpu:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Requested",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(kube_pod_container_resource_requests:memory:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Used (from netto)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(node_memory_MemUsed_bytes:sum{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Used (from requested)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:memory:running{role=~\"$noderole\"})\n*\nsum(container_memory_working_set_bytes:sum{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Limits (from netto)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(kube_pod_container_resource_limits:memory:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Requested (apps)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Used (apps)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Wasted (apps)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n-\nsum(container_cpu_usage_seconds_total:sum_rate5m{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n> 0"
      }
     ]
    },
    {
     "title": "Cores Limits (apps)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Requested (apps)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Used (apps)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Wasted (apps)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n-\nsum(container_memory_working_set_bytes:sum{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n> 0"
      }
     ]
    },
    {
     "title": "Memory Limits (apps)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Requested (k8s)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Used (k8s)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Wasted (k8s)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n-\nsum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n> 0"
      }
     ]
    },
    {
     "title": "Cores Limits (k8s)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Requested (k8s)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Used (k8s)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Wasted (k8s)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n-\nsum(container_memory_working_set_bytes:sum{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n> 0"
      }
     ]
    },
    {
     "title": "Memory Limits (k8s)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Requested",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Limits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Requested",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemUsed_bytes:sum{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Limits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "CPU Cores by Node",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum by (node) (kube_node_status_capacity:cpu:sum{role=~\"$noderole\"})"
      },
      {
       "expr": "sum by (node) (kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"})"
      },
      {
       "expr": "sum by (node) (kube_pod_container_resource_requests:cpu:running{role=~\"$noderole\"})"
      },
      {
       "expr": "sum by (node) (node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})"
      },
      {
       "expr": "sum by (node) (node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})\n/\nsum by (node) (kube_pod_container_resource_requests:cpu:running{role=~\"$noderole\"})"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"}[1d]))"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"}[1d]))\n/\n(sum by (node) (kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve))"
      },
      {
       "expr": "sum by (node) (kube_pod_container_resource_limits:cpu:running{role=~\"$noderole\"})"
      },
      {
       "expr": "sum by (node) (kube_pod_container_resource_limits:cpu:running{role=~\"$noderole\"})\n/\n(sum by (node) (kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve))"
      }
     ]
    },
    {
     "title": "Memory by Node",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (node) (kube_node_status_capacity:memory:sum{role=~\"$noderole\"})"
      },
      {
       "expr": "sum by (node) (kube_node_status_allocatable:memory:sum{role=~\"$noderole\"})"
      },
      {
       "expr": "sum by (node) (kube_pod_container_resource_requests:memory:running{role=~\"$noderole\"})"
      },
      {
       "expr": "sum by (node) (node_memory_MemUsed_bytes:sum{role=~\"$noderole\"})"
      },
      {
       "expr": "sum by (node) (node_memory_MemUsed_bytes:sum{role=~\"$noderole\"})\n/\nsum by (node) (kube_pod_container_resource_requests:memory:running{role=~\"$noderole\"})"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemUsed_bytes:sum{role=~\"$noderole\"}[1d]))"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemUsed_bytes:sum{role=~\"$noderole\"}[1d]))\n/\n(sum by (node) (kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve))"
      },
      {
       "expr": "sum by (node) (kube_pod_container_resource_limits:memory:running{role=~\"$noderole\"})"
      },
      {
       "expr": "sum by (node) (kube_pod_container_resource_limits:memory:running{role=~\"$noderole\"})\n/\n(sum by (node) (kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve))"
      }
     ]
    },
    {
     "title": "Nodes with Memory Pressure",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (kube_node_status_condition{condition=\"MemoryPressure\", status!=\"false\"} * on(node) group_left() kube_node_role{role=~\"$noderole\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Nodes with Disk Pressure",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (kube_node_status_condition{condition=\"DiskPressure\", status!=\"false\"} * on(node) group_left() kube_node_role{role=~\"$noderole\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Nodes with PID Pressure",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (kube_node_status_condition{condition=\"PIDPressure\", status!=\"false\"} * on(node) group_left() kube_node_role{role=~\"$noderole\"})",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity Management - Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cores Requested (from netto)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(kube_pod_container_resource_requests:cpu:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Requested (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "apps"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "k8s"
      }
     ]
    },
    {
     "title": "Cores Requested & Allocatable",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (requested)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (requested)"
      },
      {
       "expr": "sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n-\nsum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor",
       "legendFormat": "allocatable (netto)"
      }
     ]
    },
    {
     "title": "Memory Requested (from netto)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(kube_pod_container_resource_requests:memory:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Requested (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "apps"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "k8s"
      }
     ]
    },
    {
     "title": "Memory Requested & Allocatable",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (requested)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (requested)"
      },
      {
       "expr": "sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n-\nsum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor",
       "legendFormat": "allocatable (netto)"
      }
     ]
    },
    {
     "title": "Cores Used (from netto)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Used (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "apps"
      },
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "k8s"
      },
      {
       "expr": "sum(node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "nodes (total)"
      }
     ]
    },
    {
     "title": "Cores Used & Allocatable",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})",
       "legendFormat": "nodes (total)"
      },
      {
       "expr": "sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n-\nsum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor",
       "legendFormat": "allocatable (netto)"
      }
     ]
    },
    {
     "title": "Memory Used (from netto)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(node_memory_MemUsed_bytes:sum{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Used (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "apps"
      },
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "k8s"
      },
      {
       "expr": "sum(node_memory_MemUsed_bytes:sum{role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "nodes (total)"
      }
     ]
    },
    {
     "title": "Memory Used & Allocatable",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(node_memory_MemUsed_bytes:sum{role=~\"$noderole\"})",
       "legendFormat": "nodes (total used)"
      },
      {
       "expr": "sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n-\nsum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor",
       "legendFormat": "allocatable (netto)"
      }
     ]
    },
    {
     "title": "Cores Used (from requested)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:cpu:running{role=~\"$noderole\"})\n*\nsum(container_cpu_usage_seconds_total:sum_rate5m{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Used (from requested)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\nsum(kube_pod_container_resource_requests:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps"
      },
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\nsum(kube_pod_container_resource_requests:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s"
      }
     ]
    },
    {
     "title": "Cores Used & Requested",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (requested)"
      },
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (requested)"
      }
     ]
    },
    {
     "title": "Memory Used (from requested)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:memory:running{role=~\"$noderole\"})\n*\nsum(container_memory_working_set_bytes:sum{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Used (from requested)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\nsum(kube_pod_container_resource_requests:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps"
      },
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\nsum(kube_pod_container_resource_requests:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s"
      }
     ]
    },
    {
     "title": "Memory Used & Requested",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (requested)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (requested)"
      }
     ]
    },
    {
     "title": "Cores Wasted (from requested)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:cpu:running{role=~\"$noderole\"})\n*\n(\n  sum(kube_pod_container_resource_requests:cpu:running{role=~\"$noderole\"})\n  -\n  sum(container_cpu_usage_seconds_total:sum_rate5m{role=~\"$noderole\"})\n)\n> 0"
      }
     ]
    },
    {
     "title": "Cores Wasted (from requested)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  sum(kube_pod_container_resource_requests:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n  -\n  sum(container_cpu_usage_seconds_total:sum_rate5m{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n)\n/\nsum(kube_pod_container_resource_requests:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n> 0",
       "legendFormat": " apps (wasted)"
      },
      {
       "expr": "(\n  sum(kube_pod_container_resource_requests:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n  -\n  sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n)\n/\nsum(kube_pod_container_resource_requests:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n> 0",
       "legendFormat": "k8s (wasted)"
      }
     ]
    },
    {
     "title": "Cores Used, Requested & Wasted",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n-\nsum(container_cpu_usage_seconds_total:sum_rate5m{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n> 0",
       "legendFormat": "apps (wasted)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (requested)"
      },
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n-\nsum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n> 0",
       "legendFormat": "k8s (wasted)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (requested)"
      },
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (used)"
      }
     ]
    },
    {
     "title": "Namespaces Wasting CPU Cores",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{role=~\"$noderole\"}) by (namespace)\n-\nsum(container_cpu_usage_seconds_total:sum_rate5m{role=~\"$noderole\"}) by (namespace)\n> 0",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Wasted (from requested)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:memory:running{role=~\"$noderole\"})\n*\n(\n  sum(kube_pod_container_resource_requests:memory:running{role=~\"$noderole\"})\n  -\n  sum(container_memory_working_set_bytes:sum{role=~\"$noderole\"})\n) > 0"
      }
     ]
    },
    {
     "title": "Memory Wasted (from requested)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  sum(kube_pod_container_resource_requests:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n  -\n  sum(container_memory_working_set_bytes:sum{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n)\n/\nsum(kube_pod_container_resource_requests:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n> 0",
       "legendFormat": " apps (wasted)"
      },
      {
       "expr": "(\n  sum(kube_pod_container_resource_requests:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n  -\n  sum(container_memory_working_set_bytes:sum{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n)\n/\nsum(kube_pod_container_resource_requests:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n> 0",
       "legendFormat": "k8s (wasted)"
      }
     ]
    },
    {
     "title": "Cores Used, Requested & Wasted",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n-\nsum(container_memory_working_set_bytes:sum{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n> 0",
       "legendFormat": "apps (wasted)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (requested)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n-\nsum(container_memory_working_set_bytes:sum{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n> 0",
       "legendFormat": "k8s (wasted)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (requested)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (used)"
      }
     ]
    },
    {
     "title": "Namespaces Wasting Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{role=~\"$noderole\"}) by (namespace)\n-\nsum(container_memory_working_set_bytes:sum{role=~\"$noderole\"}) by (namespace)\n> 0",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Cores Limits (from netto)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(kube_pod_container_resource_limits:cpu:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Limits (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "apps"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "k8s"
      }
     ]
    },
    {
     "title": "Cores Limits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s"
      },
      {
       "expr": "sum(kube_node_status_allocatable:cpu:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n-\nsum(role:kube_node_status_allocatable:cpu:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor",
       "legendFormat": "allocatable (netto)"
      }
     ]
    },
    {
     "title": "Memory Limits (from netto)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)\n*\nsum(kube_pod_container_resource_limits:memory:running{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Limits (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "apps"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\n(\n  sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n  -\n  sum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor\n)",
       "legendFormat": "k8s"
      },
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable:memory:sum * on(node) group_left(role) kube_node_role{role=~\"$noderole\"})\n  -\n  sum(kube_node_status_allocatable:memory:avg * on(node) group_left(role) topk(1,kube_node_role{role=~\"$noderole\"})) * $sparenodesfactor\n)\n*\nsum(kube_pod_container_resource_limits:memory:running * on(node) group_left() kube_node_role{role=~\"$noderole\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Memory Limits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s"
      },
      {
       "expr": "sum(kube_node_status_allocatable:memory:sum{role=~\"$noderole\"}) * (1 - $nodecpumemreserve)\n-\nsum(role:kube_node_status_allocatable:memory:avg{role=~\"$noderole\"}) * (1 - $nodecpumemreserve) * $sparenodesfactor",
       "legendFormat": "allocatable (netto)"
      }
     ]
    },
    {
     "title": "Cores Used (from Limits)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_limits:cpu:running{role=~\"$noderole\"})\n*\nsum(container_cpu_usage_seconds_total:sum_rate5m{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Used (from LImits)",
     "type": "timeseries",
     "description": "Not all workloads have limits defined but still use CPU resources. Thas why the usage can be higher than the limits.",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\nsum(kube_pod_container_resource_limits:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\nsum(kube_pod_container_resource_limits:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (used)"
      }
     ]
    },
    {
     "title": "Cores Used & Limits",
     "type": "timeseries",
     "description": "Not all workloads have limits defined but still use CPU resources. Thas why the usage can be higher than the limits.",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (limits)"
      },
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\"} * on(node) group_left() kube_node_role{role=~\"$noderole\"})",
       "legendFormat": "k8s (limits)"
      }
     ]
    },
    {
     "title": "Memory Used (from Limits)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_limits:memory:running{role=~\"$noderole\"})\n*\nsum(container_memory_working_set_bytes:sum{role=~\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Used (from Limits)",
     "type": "timeseries",
     "description": "Not all workloads have limits defined but still use Memory resources. Thas why the usage can be higher than the limits.",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\nsum(kube_pod_container_resource_limits:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})\n/\nsum(kube_pod_container_resource_limits:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (used)"
      }
     ]
    },
    {
     "title": "Memory Used & Limits",
     "type": "timeseries",
     "description": "Not all workloads have limits defined but still use Memory resources. Thas why the usage can be higher than the limits.",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace!~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "apps (limits)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace=~\"kube-.*|cattle-.*|openshift-.*\", role=~\"$noderole\"})",
       "legendFormat": "k8s (limits)"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores Usage by Node (absolute)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by (node) (node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU Cores Usage by Node (%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (node) (node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})\n/\ncount by (node) (node_cpu_seconds_total:sum_rate5m{role=~\"$noderole\"})",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage by Node (absolute)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemUsed_bytes:sum{role=~\"$noderole\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory Usage by Node (%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (node) (node_memory_MemUsed_bytes:sum{role=~\"$noderole\"})\n/\nsum by (node) (kube_node_status_capacity:memory:sum{role=~\"$noderole\"})",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem Usage by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{mountpoint!~\"/run.*\"}) by(mountpoint,instance) * on(instance) group_left(node) instance:kube_node_role{role=~\"$noderole\"}\n-\nmax(node_filesystem_avail_bytes{mountpoint!~\"/run.*\"}) by (mountpoint,instance) * on(instance) group_left(node) instance:kube_node_role{role=~\"$noderole\"}",
       "legendFormat": "{{node}} ({{mountpoint}})"
      }
     ]
    },
    {
     "title": "Filesystem Usage by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  max(node_filesystem_size_bytes{mountpoint!~\"/run.*\"}) by(mountpoint,instance) * on(instance) group_left(node) instance:kube_node_role{role=~\"$noderole\"}\n  -\n  max(node_filesystem_avail_bytes{mountpoint!~\"/run.*\"}) by (mountpoint,instance) * on(instance) group_left(node) instance:kube_node_role{role=~\"$noderole\"}\n)\n/\n(max(node_filesystem_size_bytes{mountpoint!~\"/run.*\"}) by(mountpoint,instance) * on(instance) group_left(node) instance:kube_node_role{role=~\"$noderole\"})",
       "legendFormat": "{{node}} ({{mountpoint}})"
      }
     ]
    },
    {
     "title": "IOWait by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(rate(node_cpu_seconds_total{mode=\"iowait\"}[5m])) by (instance) * on(instance) group_left(node) instance:kube_node_role{role=~\"$noderole\"})\n/\n(count(node_cpu_seconds_total{mode=\"idle\"}) by (instance) * on(instance) group_left(node) instance:kube_node_role{role=~\"$noderole\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Read Storage Troughput by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "node_disk_read_bytes_total:sum_rate5m{role=~\"$noderole\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write Storage Troughput by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "node_disk_written_bytes_total:sum_rate5m{role=~\"$noderole\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Read Storage IOPS by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "node_disk_reads_completed_total:sum_rate5m{role=~\"$noderole\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write Storage IOPS by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "node_disk_writes_completed_total:sum_rate5m{role=~\"$noderole\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Read Wait by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_disk_read_time_seconds_total:sum_rate5m{role=~\"$noderole\"}\n/\nnode_disk_reads_completed_total:sum_rate5m{role=~\"$noderole\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write Wait by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_disk_write_time_seconds_total:sum_rate5m{role=~\"$noderole\"}\n/\nnode_disk_writes_completed_total:sum_rate5m{role=~\"$noderole\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive Network Bandwidth by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "node_network_receive_bytes_total:sum_rate5m{role=~\"$noderole\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Transmit Network Bandwidth by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "node_network_transmit_bytes_total:sum_rate5m{role=~\"$noderole\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Receive Network Packets by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node_network_receive_packets_total:sum_rate5m{role=~\"$noderole\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Transmit Network Packets by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node_network_transmit_packets_total:sum_rate5m{role=~\"$noderole\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Receive Network Packets Dropped by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node_network_receive_drop_total:sum_rate5m{role=~\"$noderole\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Transmit Network Packets Dropped by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node_network_transmit_drop_total:sum_rate5m{role=~\"$noderole\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}