---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: private-key-verifier
  namespace: billing
spec:
  encryptedData:
    PRIVATE_KEY_BASE64: AgAfLtd04NhLkPIpY6nHB7Mdmet9HqTJXD5kgG/Lj+i8KXu9H5fup6nuRGv40P7u5sKDpaSGYcOP9x+eqbUL8iRBsuGrmAgZWFBIEK52FZQz3IJWtfAxL7xvGPhCCXjortI+QorIe0QaRF1S733BOR6hPaBwMm2pE3Tx7b/Pj5TtfscH1eGkvPuH4MhIQLgie4QBvp4OTSy6/elO1zXVKpJ1L0NkgATRalIlvc8UGRWtOK8QKRwMgV1pWKimxK+r1tWv8/2wHm6/oh7FIoQW/M8HJ25TeqfstEUxSm0279iVIwc82B4Z6rErk+GNt5zrCZzxLm8wvqQ5rktYbuLkbk0S3PBqZaUMpHDiXkRnwbm5WS4T50zZyZV9fSzKHWWR/x3tHb4uK5hhvD5zrLEE7TIuW+n0SRrOjJqIyK5Aro4+5WMrxSp9jhLqSXMe5ix38Y02NFFB9aTVSohRT2uipz83rATsauvrLOhg9Vf++3EfL10TyM+g3ai3Qwxe7YxoTCoFeDvdbCc4DJs85E/Xdcacg7d5ryyUWF4YBiWPs+3cWU5GYXrDHnIy/J8AI/8sv9Ajbr6m2dAnrJb4+Cya85hMhzpl2Dqkkcv+GU4Aikn40ZZ7leKvdzKcze639BT3np22TbES35ED0HvsQJEP8l34u4/LfC6y+BgTe7XqJAWkW5zfkUDvXN36g8/1rwsoq/EYAbES85uNdueVDupQVXHGKkwtaWWjsjEcat+pM90GGQ==
  template:
    metadata:
      creationTimestamp: null
      name: private-key-verifier
      namespace: billing
