---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: private-key-verifier
  namespace: billing
spec:
  encryptedData:
    PRIVATE_KEY_BASE64: AgBJN7LX2AqOrq6+y7VoUNf6Za6aJ1RWO5+veezxW8RFvgeRFgBycQg7QOk+9hcqSRO+OQVp0QhhKo0snVCEUbRdpg28qlbNld1JkH5E6iYGorlaVO1RFdKZ/lvZugduzZ7KD8mbZo6B03zGYm2zULqbYXfc2+z698NHL+XLLDpvwOmrn1x11Y5U3aOnnm6z1ctnMBhUlYH/cSKeaD6jh+CUkznnV8F/eoFkY+Hs5Irb1NlHlabY8tQhNV7ymKMCK3gDAyxmgD5wN/N1eYymRWa4ez8gD9/I8gUXMCkNbcrZ7vQ9hsph5NmcwHT5vTfGgppTXx8RW/z86PrKqDhwmZwW/k0UuahoRkcD0VOizRdnQfvxwNVwS9Nqw/bmEcPVI3hHZjTus31I+636kKzXbept1ayDx8BZSHTs0wHFu7y/0kSXUbctLihNoHILd/ATumXeBLjGmfBE70x39OWTi1UtB8VpGF/2pjDbKWsyF/xbh3O5JrEBGVs5n0lDSqjEWG1QDE/8EV1HrS36FcblTUKrVVBuf/o/P9c68b5cAIcHmxkxzOarak8OMQlTfkfFFi5E8tbIWLSsEQK3i8Nfd9zuZMxatwriaVjNyZn+KONaVx1sTgNTITcwjxKpHJqEhRcFRiwmAlX+SqoC47XPHVhhkCxvbS0Qfljip83UPtdRia4eLdY30BdZGCrXO3Q2sHWl1URiYzZjkzfHMKM+fy2IF+fiwrf9nSFiTnz4mej1ZBzabnDDxFFIRhhLYA==
  template:
    metadata:
      creationTimestamp: null
      name: private-key-verifier
      namespace: billing
