apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    purpose: security
spec:
  project: default
  sources:
  - repoURL: https://aquasecurity.github.io/helm-charts
    targetRevision: 0.36.0
    chart: trivy-operator
    helm:
      releaseName: trivy-operator
      valueFiles:
      - $values/ionos_sbx/security/trivy-operator/values.yaml
  - repoURL: https://github.com/DOME-Marketplace/dome-gitops
    targetRevision: HEAD
    ref: values
  destination:
    namespace: security
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
