---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: scorpio-secret
  namespace: marketplace
spec:
  encryptedData:
    postgres-password: AgAIG10rBHcWvsUUvyqbhvTzKTpphi4f3hOb6Pc6zhaE2ldQdAvTsm+Pk06/qADgEX4y0Aa4BPdeE1I5qavY0GrFb4drix97v9knLF7tlx/vPT1LFotLOONpthTKHKh0dA5K5n+q18OGPxW9ipG56pFrHl3C/fvfgQkg5dh94J+GxZmqo2G/1lv7ENG8KAXALfujIU/4gawXJUAdbNEesV33ujjeujY3MCcd8V2ubLr6vgJqoNhCFfnTc9Rt2oDgwi2S9PC3Ibr1bqXFUks+oZyDJwmbWHHrqTViL0NuUc54hsIkFHyiM52zfR09ghZS4R0O+4TIuyQrvPcesbcapCpYkaEMljDNHxf87/oB0/fGHjcMjZZj8rQ8ZvWZHCoVyUsSgf9g/EqQOxiHXjMIzPYkgz2sdFg7BXCOF0luY0Yo9F1O6Dj3aR5dM7Y7ObKXY1Ojw2d47FxRNscDuLZ2L/uifhZ/zSuENvIGK7lkCQq46ocFWb/LCRd5sJqhOh97Rtjf0RsjfOhHTkpDhScevOVLLNLlfr1VmEjWEZbIgJsKX/CmVCjsDYxb6MtsMDUsSfo5dvt5aQhYqEjSsg6G8ESGXaP7XVQFXIYFRLe5qjE7mUuqzIZXzRZ9NrMyWHNA3UHy2DWbSha3xsUbKEgUerrqZY9Cx2HtUCHlPkfIsmr7GMQfeWaZZtxF8znBLQV+juoQ2+5ct8xuOKHXY6M=
    postgres-ionos-password: AgB+EGa9ng37Ko72d7SalxUeWhB0f6wIRHgwyjsv1gc6njLz/MJqb5nPdB8dCWmrPljVFuiWCA5OUHaGNCc0g2mCYFYpFCqjtD+0nzIVEcELBcAE9xgVSp8MChX18oyxoaOHYRml6GwIICHVUDjox81l41eufJnoMrXovZAuq6XZTa1ex8AMGeN0pQWugui0P3XlHVyRBOZDjKS3S14fPQCnNVzgptnzOWT+i2SNmLnGiiVv92ltyDekn6j1JcFA9NmyTvfKJ0D0a/dGQnPGIqC2s4Esmz8cZk7WzOVgS3sAzADvENnmIciGGPNAT+y3M+GytEeKrvcLMo9/11fUC+PvYYiKn7vfUMl89XK/6UDnmmuKjjtrzejrb49jKLIS1zNumeQxRaRzvo6pXnWd3uMkBdDngr4yddztOLazZt2sGem7WBYFO2anNEAVZsWaq2ZD7TpI2YtSyYMZhs93UB4/OjkMyrarjBaCHyqxb1zH5IdQR/A6HDv9Di0AY46VbFswKZQ1fEUu82ZDchOsTYrbSfiqli9P64DQDTVGVdedeB/NAda4EDExGzGpqMZ3w+kSxrRogXUuCxCR8yTGRfNUUhKQ65yKzwUXDnM9FNbRkpn+uxk/S3r6U+Gt7LcD1iZrdZZe+jLCe5ril+Kt/sN+uyhZuj+gE8zQqGBGsxRhhiMqzq1c/n8eeKIBBmRWqbvyY4d/eDmTyLJozylixXM=
  template:
    metadata:
      creationTimestamp: null
      name: scorpio-secret
      namespace: marketplace
