apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tmf-test-sbx
spec:
  secretName: tmf-test-sbx-tls          
  issuerRef:
    name: letsencrypt-sbx-issuer
    kind: ClusterIssuer
  commonName: tmf-test.dome-marketplace-sbx.org
  dnsNames:
    - tmf-test.dome-marketplace-sbx.org
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
