apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-routes-config
  namespace: caddy-proxy
data:
  sbx-site.caddy: |
    tmf-test.dome-marketplace-sbx.org {
        log {
            output stdout
            format json
        }
        rate_limit {
            zone per_ip {
                key    {remote_host}
                events 100
                window 1m
            }
        }
        request_body {
            max_size 1MB
        }
        header {
            Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
            X-Content-Type-Options    "nosniff"
            X-Frame-Options           "DENY"
            Referrer-Policy           "no-referrer"
            Permissions-Policy        "geolocation=(), camera=(), microphone=()"
            -Server
            -X-Powered-By
        }
        encode zstd gzip
        handle_path /tmf-test/get-route* {
            reverse_proxy account.tmf-test.svc.cluster.local:8080 {
                transport http {
                    dial_timeout            5s
                    response_header_timeout 60s
                }
            }
        }

        handle_path /ticketing/* {
            reverse_proxy zammad-nginx.zammad.svc.cluster.local:8080 {
                header_up Host ticketing.dome-marketplace-sbx.org
                transport http {
                    dial_timeout            5s
                    response_header_timeout 60s
                    }
            }
        }

        handle {
            respond "Not Found" 404
        }
        handle_errors {
            respond "Error {err.status_code}" {err.status_code}
        }
    }