---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: caddy-proxy
spec:
  encryptedData:
    .dockerconfigjson: AgCBO1x6AFYq7FD2jYyuxzTzX38IHdDzsf6+Sv75DvadKqvlu3v9rYPzCDGz1KbmT4RspPjTnvpwZIs3jm7yjfB2So8x2FtCJlZAq0ZwnbngdiqCzJ44jXkkbyeHzN6W5+tbWDNL6rYLOJzI/YgvO+NbSb2QkIh2jI+P8OFW0wiJGpkdm6OnnR8EqpzSpbf+6yYkL2QNCgYqaqxdVvztR2LLWOaSL8WwbWnnOfX10QZJRSrQ3fq89vlwDZBn8Cg+FkWZ2XXE+0q8mktNaQZtqR3BpejR6pLxDsnLZTINg4abF+NdnbvG0BJ2fl8RWtQKYsYwfhNumuSx6yjuJ1wByjMi914X2VxuU7f7wSu4fEwDwMK8tSCcd588ESDQFTge4j4derDWFGEMzEy7a3EldndvLNdXAoQkJ38b7zbc0BTHUDH4CVkFFmpzqiro1pL+gBXQwyAFygGNtSwvoJH2HtD/BD09MJeCDb95q7cN1E5TowVLP1q3Mx384hJgsB+Bgc6PRfhO6ADuaiF0QRL8CyQggWdxjrE5on7UwMuQ6Yhxvya5T07TNxzw1+UB2NoTCo4k1+nXz+lte9prMFK7otsWrLhn4GyrZmwachI8ZU6Dy0xx8H9RAS8NLOb8Qv0Ze2BzI3NSVrGW9WXEnYMFgwClv9P5t/9LZ1zBtJwc9qhEYtlLOijZlB15dP0DF8SMwFeUxk2fLKIe0BBCGTupp/pooH0zBOGSieuLO4IH520jKbEPZr8gQj6o5hFS1mHPwW6F6rn/KQXhE6ERT+mBhFRfL6N3etoYIqIvg0RWUASAw8M/uLeZgd5qagaNQeSB//VjmEBLOMAWiumVG/1/BV84XEdGyBYta13LROJoP18GowJz9ZW/P3rgzAfXxDAN4JQOtU4evL5gm+DLecjYp/W6cE5QZvecC/OUWBqc5tBm8RUs8jKW3op07YSmRnNLw/rnX20=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: caddy-proxy
    type: kubernetes.io/dockerconfigjson