---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: reverse-proxy-pull-secret
  namespace: caddy-proxy
spec:
  encryptedData:
    .dockerconfigjson: AgCRiXHCcqTa2DS1vfUhq+3b6VDWkAGGpzwVt0PzM8fnJqEtG+mXXHI58x7RVHTAQ48MyldV6XlpgOf5YeyCwvvjhOepTAUX2b0Q+y+tMTUBDeChROYQSHFnitjzaiqKzlmzanEkVKUsdWPhPgCqD99HgZ0XXjntk0ETSntUPuEy/+zxKEC+9h829zR9TA9GfmCQGUk03FnmTVSE/hVyU5q7RdBLvNNh0a3IKW2RZvFny9SLLoe2IOuD1mfzEVUXelQUm5twfvFepWUFJDFJ8Pilzu4GYrmdVr9VdL/1nrFSPhOuPgedTydB0Pa2jsS5PImHRviy8iiAJ1//JO4CFjyzLogPqbvGuaSnP5AuxxKkWLxkRFIo5V3pPZ9h5L318Y6pyOSlKkxITMbSCEBkaohRaia6rx2wN7/JNzIpekLR8dmvPinOF2gbKl9aY78OMUQTpc/zAYAZuDqfynKkok3RRShQtERDE6wfQqdDjPK8XQRpvNqvJeB8YVTwtlLhME7sOhGYmEVfRKdfiy+e0v3KQGFCjQYlkyNTJqL6gYikA86n/BwcCqZlKpBEOpFoPpysN6k+S3V+m+nUUTUAFRMh1nTPVJ/CsLBroTihsYqCL82SxwK2IZnuowFgeaqc5yC2YAc9DopogMRGSNlqs7wJ5PJfAdyxt33KLCq28EeJttTN8yy4w43qjvBUatR8WNKALVuQTF8iqkKapYO+/2prGT8pfs2RjA/zvwAAJtjoFlU6bDjhGHBw7AR9kqcRLWvfdw/h79c4Y0j4/pnWELE9ONJkPc84wdl/uWvbYpYeS5U+QiSUFuYiIwMg+LrY2Vvk1V7yCIiAYCeDHg7Z7ohT45vO98TRREKxeZiYUptsoJFAelMFZBUhe626t1kV3OsyzZGbw4BgNJMguBG8rNqNHF95esZd74GnVOQs4etsRHWT
  template:
    metadata:
      name: reverse-proxy-pull-secret
      namespace: caddy-proxy
    type: kubernetes.io/dockerconfigjson
