apiVersion: v2
appVersion: 6.3.0-20
dependencies:
- condition: zammadConfig.elasticsearch.enabled
  name: elasticsearch
  repository: https://charts.bitnami.com/bitnami
  version: 19.17.0
- condition: zammadConfig.minio.enabled
  name: minio
  repository: https://charts.bitnami.com/bitnami
  version: 13.2.0
- condition: zammadConfig.memcached.enabled
  name: memcached
  repository: https://charts.bitnami.com/bitnami
  version: 6.9.0
- condition: zammadConfig.postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.12.10
- condition: zammadConfig.redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.17.1
description: Zammad is a web based open source helpdesk/customer support system with
  many features to manage customer communication via several channels like telephone,
  facebook, twitter, chat and e-mails.
home: https://zammad.org
icon: https://raw.githubusercontent.com/zammad/zammad-documentation/main/images/zammad_logo_600x520.png
maintainers:
- email: monotek23@gmail.com
  name: monotek
- email: enjoy@zammad.com
  name: mgruner
name: zammad
sources:
- https://github.com/zammad/zammad
- https://github.com/zammad/zammad-helm
version: 12.1.0
