---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mail-relay-secret
  namespace: mail-relay
spec:
  encryptedData:
    password: AgBLZYZKwNIG7OwWB8kzR0VemOXHli6feHQIFdsfhNCrPMUght8YxTyO6MHrx6ZvUxJSqIkqbYnAXJxtnUcsVNi/Avi0Tjy5c5jIIbRVdmr5wLx7SSEIkmvGRBK2RPMqVrxhZLSpfP8liZ7RnqX6pL5XkiyA7XHbHxDzLXBgKYKtQT2I8P6zqZH1o/VH8Tso7uvp6PHy2sUCjRHPFSIKoJHe74lXo0ewVrOyFLkscyaM7Hdm4UXuNFiaXwILh7x9Wy0zHx8xhNuFWCsapX9OxHdLdc+qgnfXr/HqinYZ0/pdB8AJLRVkXlAbZmdRlqhfqcHDKfXMDSXrYH6lc3v9lbZcx6WNIEQO0namee24YOcTeP6bqDqwkYR9Uy0kiUcbK6tJhKtVBvA95gTuTqTu4+xJCC2G3aNRcWevmfYwGfuzpg5TuHWy/oDJUVydbdVS2K1ArrLZrGaiCXuvyBC9+BaMMm17HcjGpWDCOodb2PGY6UB+X4kGjlPT8U/iwwlDa3aLhd7/w7WIwSBqkXWz8U8ROIGh2M2MlN2y31AQqUCg0W2fd25lcHSUxT3m13t9ppycr0nxCj447FdD4xeHl9W6jLzL0xN3dQsQ4A9lWODE9FH3NlOpTgEtSh1SCHkFebW5EqS9pEaGLwv17zPx78k+FpqFh9PML/mD0hP5wQ0CAznaskn+STJrDB+9IUpHwjdKVRERICfuGN4=
    username: AgBVBcgWpkIJk3dvVFe2EXMOZJkTAOtLtJP+L7mfN8V+SZg1H6OP/jLMSMHdMZehjJn9/uJeGPvBCfYG0i+pewWxC85e/Sh/c8YvkanaQNPgBYlKBK12PP4RprmnfsaNyLn7SCS87RyztPEwTV3+xnydEihNHkWNZeIUlVnp/soeFRWiNUIPVilWOyzh8k4AKSAb8o9uboyR4PwamLCW8M0rQnxzd+eez1zujSOnk5KCqFpRDbf0iUmyj43PymBHPIASsrMr06Eg4Y61F5yTCe5nRDzQA6t272ts5s72yl3Bb1LrO67PCkw1GLilfEofy0T2hieCX+VlmQYV58YccQd5mwl9iGINHoTX/gNY/JeziVbVWba8KHwVtmGmhHFDx4uBfrqzSsi7OYJH9qk+ZJr38NXlyh5+KT5yUSHaOrHiFuwPR8fmCXcS0ui6cbAxHo/muNWP9+d2uEXUsvu05/r8f7ifHRfJcuUQMhHJo9lHccvWgPnIykccR7zcZ3o5lt7lJcEfPYz85Zte+4Q518sHlAjZn2IhLCY+xUEX5Eg1afhPYxM0Xezq+2bHQ7x12+sxYpaEBLwasaozw4BdTWQGXV8LeMzWBxnO72h92Y7lfo/W8jBLLSPQT172e1OG1PHbVI6eVzomMUW0vlDulHUGdTrFr1ZmBeqdj3d1lAu/7xmu4oscZ1TRhonbG1umfoqfyuEhfpbKg5ry8Xdz46MRSUHGZb9ppbaR2gbaQPYtVeE3ZRI=
  template:
    metadata:
      creationTimestamp: null
      name: mail-relay-secret
      namespace: mail-relay
