---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-s3-credentials
  namespace: loki-distributed
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBlNMuBdtRvADeZ33VD/jtT7tV3gyoLNVX3xXarOZT17HQP/az+/q6XuqED+8zw6S5HYJ5p4+vOL2wSOKIWPGPpju5YMC6uRXx4EppjlhWoh/JUWDqkMydpgZD4OlyD+tHe0cLs8ELD8leTFpP8HMAjXNv3YTroWONHPH5iilWRwfzl3lXb4ITOM7/F45eXNnP4QEqVeKBtNab8RpaUOd6RaopJif/wmQj+QmfrExGFrR1YUUdoNfj8AhdlaYyHle5c0X1sNRFh611io3pyGpILoypyOYyjOrV1iVCIe98W6+RFORxz4UUex4R4o7o43xYQfVQhFtzYBqXwYbGla426LPM0h0ZeTizT0Q/raI24Zot2xaF4Buw/FXHgRLJiUtD0eH5pG1jqiNbI2eQp1nX6UFEbUJ7sNoCiYdKFhfaX4StCkpecADH8kUIcAeQsHw6ntqVVbVTPSlkbKEcLREHV8NioYStcXWhnvsNQZOI+X76kSitRqrvvi7hkoCvY4vqgphPyUuzZCe2Br3XrsULXU/QzWHhkWRhEURPJsTdqI+4Se3l6LGYeZtUVn+dcgjuomPZPRdnbP30bkPrhjgLyylXJXcaHX8aSJchHsUhDdjH53FL7sbxU2KjvCQGEejgNlL8LbAVFqZxQEYaj4Z2OF/OMPC3gic7TvrKBjBC8GsrqIKxks2MpWdsEdAJYRS4XM641w2RjZs46L+B7rDSWTKoK6HOPVXqg8htWUolvnsDNbuYjeakykfZyy/RFuXUnwEaSvi5zdKUYDSW+7G9xIwzz9KvUgCnQkU/LjhMB7hrBC2K0EsA/4Lg59Q==
    AWS_SECRET_ACCESS_KEY: AgAYgAKbc2VQ0Rbt7LbYpsPDkuBy3il9gQU7t5dTAVU4CDVdp0VEQSSnUDbS6V4OKYX1AOLoJZqBvxU27H9lQjt39QGioaqWoiPtCvsp22Vu/mzDsXXUzQYKT7IVOivhY/qPnwtpWhByq59bvDoluGb2AMeNngVDXAshKyxxS+N+VJ0nWCBFoTZHb5mqI0Krz1Q5ZeTgvdl57xsDtfzjLjHJyMLxtPBZ96uU0UB3LgZRcZlIQwlne40XI6nHgv45skFGED/0aE1DFN9UYJ7550eLga1dgbNO6Re3f+0bBc9vmBvdtIRy4dhqFn0RVPyq+bZ0OOGxOCBB2L+8Ktjcvd4iuKSuIJbxq2kKFAStmT+yLY8FWrW/2Qsj3GzxzlzZZxl+5VjKpilOvQcb7IV5H3BBMTfuHUJjpDHXAT8qwwpeHv/taArEUoly+PAQpDfR1K9WM1Gzo5V3CogBjWb9+2d4rFHvNumqhchqfJL+vkKr/vkT1hCXYDcKOC5h56VP7yz4zuu7TB5gVZAuq2EokA1WKRnUzi3aiQJBmFmNkZ5pmdxT+YmvVBTUzUT40W90aAqjyI/i5Hy+eWiWcZIiSSEj5hmvYqucdOSYzMTNBGULS4VuCTaLWUixs4TmJw7p+yrmyat9LHY/OTeUz7XOsIueVtsYi2zKrqANsFJVpjd6Th9uvUdJhgpMXbzx+2U54IKwC8BbE6mHCcRjMkTJuSUrsJMEQhVSwd7oOX1z/oGxn7mbssPbj9uQHIWpX0f4i3AAkC4skF/wL1NVgtcQuY/M
  template:
    metadata:
      creationTimestamp: null
      name: loki-s3-credentials
      namespace: loki-distributed
