apiVersion: v2
name: caddy-ingress
description: Chart holder for argo-cd

type: application
version: 0.1.0
appVersion: "v0.2.1"

dependencies:
- name: caddy-ingress-controller
  version: 1.3.0
  repository: https://caddyserver.github.io/ingress/
