{
 "title": "Ticketing Analytics",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "OPEN TICKETS BY COMPETENCE CENTER",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    g.name AS group_name,\r\n    COUNT(CASE WHEN t.state_id NOT IN (4, 7) THEN 1 END) AS \"OPEN TICKETS\"\r\nFROM\r\n    tickets t\r\nRIGHT JOIN\r\n    groups g ON t.group_id = g.id\r\nWHERE\r\n    g.id IN (27, 26, 18, 12, 11, 10, 7, 6, 5, 4, 3)\r\nGROUP BY\r\n    g.name\r\nORDER BY\r\n    g.name ASC;"
    }
   ]
  },
  {
   "title": "ESCALATED TICKET BY COMPETENCE CENTER",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    g.name AS group_name,\r\n    COUNT(CASE WHEN t.state_id NOT IN (4, 7) AND t.escalation_at IS NOT NULL AND t.escalation_at <= NOW() THEN 1 END) AS \"ESCALATED TICKETS\",\r\n    MAX(CASE WHEN t.state_id NOT IN (4, 7) AND t.escalation_at IS NOT NULL AND t.escalation_at <= NOW() THEN EXTRACT(EPOCH FROM (NOW() - t.escalation_at)) / 86400 END) AS \"MAX ESCALATION TIME (DAYS)\"\r\nFROM\r\n    tickets t\r\nRIGHT JOIN\r\n    groups g ON t.group_id = g.id\r\nWHERE\r\n    g.id IN (27, 26, 18, 12, 11, 10, 7, 6, 5, 4, 3)\r\nGROUP BY\r\n    g.name\r\nHAVING\r\n    COUNT(CASE WHEN t.state_id NOT IN (4, 7) AND t.escalation_at IS NOT NULL AND t.escalation_at <= NOW() THEN 1 END) > 0\r\nORDER BY\r\n    g.name ASC;"
    }
   ]
  },
  {
   "title": "AVERAGE OPEN TICKET AGE BY COMPETENCE CENTER (IN DAYS)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    g.name AS group_name,\r\n    AVG(EXTRACT(EPOCH FROM NOW() - t.created_at) / 86400) AS \"AVERAGE TICKET AGE (DAYS)\"\r\nFROM\r\n    groups g\r\nLEFT JOIN\r\n    tickets t ON t.group_id = g.id\r\n    AND t.state_id NOT IN (3, 4, 7)  -- Considera solo i ticket aperti\r\nWHERE\r\n    g.id IN (27, 26, 18, 12, 11, 10, 7, 6, 5, 4, 3)\r\n    AND t.id IS NOT NULL  -- Assicura che solo gruppi con ticket aperti siano inclusi\r\nGROUP BY\r\n    g.name\r\nORDER BY\r\n    g.name ASC;"
    }
   ]
  },
  {
   "title": "RESOLUTION TIME FOR TICKETS CLOSED IN THE LAST 30 DAYS",
   "type": "table",
   "gridPos": { "h": 16, "w": 19, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "WITH ticket_state_count AS (\r\n  SELECT \r\n    group_id,\r\n    COUNT(*) AS tickets_state_not_4_7\r\n  FROM tickets\r\n  WHERE state_id NOT IN (4,7)\r\n  GROUP BY group_id\r\n)\r\nSELECT\r\n  g.name AS \"COMPETENCE CENTER\",\r\n  COUNT(t.id) FILTER (WHERE (t.last_close_at - t.created_at) <= INTERVAL '1 day') AS \"LESS THAN 1 DAY\",\r\n  COUNT(t.id) FILTER (WHERE (t.last_close_at - t.created_at) > INTERVAL '1 day'\r\n                   AND (t.last_close_at - t.created_at) <= INTERVAL '7 days') AS \"2 TO 7 DAYS\",\r\n  COUNT(t.id) FILTER (WHERE (t.last_close_at - t.created_at) > INTERVAL '7 days'\r\n                   AND (t.last_close_at - t.created_at) <= INTERVAL '14 days') AS \"8 TO 14 DAYS\",\r\n  COUNT(t.id) FILTER (WHERE (t.last_close_at - t.created_at) > INTERVAL '14 days'\r\n                   AND (t.last_close_at - t.created_at) <= INTERVAL '30 days') AS \"15 TO 30 DAYS\",\r\n  COUNT(t.id) FILTER (WHERE (t.last_close_at - t.created_at) > INTERVAL '30 days') AS \"MORE THAN 30 DAYS\",\r\n  COALESCE(tsc.tickets_state_not_4_7, 0) AS \"STILL OPEN\"\r\nFROM groups g\r\nLEFT JOIN tickets t ON t.group_id = g.id\r\n  AND t.state_id = 4\r\n  AND t.last_close_at IS NOT NULL\r\n  AND t.created_at IS NOT NULL\r\n  AND t.last_close_at >= NOW() - INTERVAL '30 days'\r\nLEFT JOIN ticket_state_count tsc ON tsc.group_id = g.id\r\nWHERE g.id IN (3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 17, 18, 27, 29)\r\nGROUP BY g.name, tsc.tickets_state_not_4_7\r\nORDER BY g.name ASC;"
    }
   ]
  },
  {
   "title": "RESOLUTION TIME FOR TICKETS CLOSED IN THE LAST 30 DAYS (BY SEVERITY)",
   "type": "table",
   "gridPos": { "h": 16, "w": 19, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "WITH ticket_state_count AS ( \r\n  SELECT \r\n    group_id,\r\n    severity,\r\n    COUNT(*) AS tickets_state_not_4_7\r\n  FROM tickets\r\n  WHERE state_id NOT IN (4,7)\r\n    AND severity <> '5'\r\n  GROUP BY group_id, severity\r\n)\r\nSELECT\r\n  g.name || ' - ' || s.severity_name AS \"COMPETENCE CENTER\",\r\n  COUNT(t.id) FILTER (WHERE (t.last_close_at - t.created_at) <= INTERVAL '1 day') AS \"LESS THAN 1 DAY\",\r\n  COUNT(t.id) FILTER (WHERE (t.last_close_at - t.created_at) > INTERVAL '1 day'\r\n                   AND (t.last_close_at - t.created_at) <= INTERVAL '7 days') AS \"2 TO 7 DAYS\",\r\n  COUNT(t.id) FILTER (WHERE (t.last_close_at - t.created_at) > INTERVAL '7 days'\r\n                   AND (t.last_close_at - t.created_at) <= INTERVAL '14 days') AS \"8 TO 14 DAYS\",\r\n  COUNT(t.id) FILTER (WHERE (t.last_close_at - t.created_at) > INTERVAL '14 days'\r\n                   AND (t.last_close_at - t.created_at) <= INTERVAL '30 days') AS \"15 TO 30 DAYS\",\r\n  COUNT(t.id) FILTER (WHERE (t.last_close_at - t.created_at) > INTERVAL '30 days') AS \"MORE THAN 30 DAYS\",\r\n  COALESCE(tsc.tickets_state_not_4_7, 0) AS \"STILL OPEN\"\r\nFROM groups g\r\nCROSS JOIN LATERAL (VALUES \r\n    ('1', 'Critical'),\r\n    ('2', 'Major'),\r\n    ('3', 'Moderate'),\r\n    ('4', 'Minor')\r\n) AS s(severity, severity_name)\r\nLEFT JOIN tickets t ON t.group_id = g.id\r\n  AND t.state_id = 4\r\n  AND t.severity = s.severity\r\n  AND t.severity <> '5'\r\n  AND t.last_close_at IS NOT NULL\r\n  AND t.created_at IS NOT NULL\r\n  AND t.last_close_at >= NOW() - INTERVAL '30 days'\r\nLEFT JOIN ticket_state_count tsc \r\n  ON tsc.group_id = g.id \r\n  AND tsc.severity = s.severity\r\nWHERE g.id IN (3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 17, 18, 27, 29)\r\nGROUP BY g.name, s.severity, s.severity_name, tsc.tickets_state_not_4_7\r\nHAVING \r\n    COALESCE(SUM(CASE WHEN (t.last_close_at - t.created_at) <= INTERVAL '1 day' THEN 1 ELSE 0 END), 0)\r\n  + COALESCE(SUM(CASE WHEN (t.last_close_at - t.created_at) > INTERVAL '1 day' AND (t.last_close_at - t.created_at) <= INTERVAL '7 days' THEN 1 ELSE 0 END), 0)\r\n  + COALESCE(SUM(CASE WHEN (t.last_close_at - t.created_at) > INTERVAL '7 days' AND (t.last_close_at - t.created_at) <= INTERVAL '14 days' THEN 1 ELSE 0 END), 0)\r\n  + COALESCE(SUM(CASE WHEN (t.last_close_at - t.created_at) > INTERVAL '14 days' AND (t.last_close_at - t.created_at) <= INTERVAL '30 days' THEN 1 ELSE 0 END), 0)\r\n  + COALESCE(SUM(CASE WHEN (t.last_close_at - t.created_at) > INTERVAL '30 days' THEN 1 ELSE 0 END), 0)\r\n  + COALESCE(tsc.tickets_state_not_4_7, 0) > 0\r\nORDER BY g.name ASC, s.severity::int ASC;"
    }
   ]
  },
  {
   "title": "OPENED TICKETS TREND",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 19, "x": 0, "y": 67 },
   "targets": [
    {
     "rawSql": "WITH intervals AS (\r\n    SELECT \r\n        generate_series(\r\n            DATE_TRUNC('week', NOW()), \r\n            DATE_TRUNC('week', NOW()) - INTERVAL '180 days', \r\n            '-7 days'\r\n        ) AS week_start\r\n)\r\nSELECT \r\n    intervals.week_start,\r\n    COUNT(*) FILTER (WHERE group_id = 18) AS \"01 - Marketing Activities\",\r\n    COUNT(*) FILTER (WHERE group_id = 27) AS \"02 - Project Website\",\r\n    COUNT(*) FILTER (WHERE group_id = 11) AS \"03 - Privacy & Legal\",\r\n    COUNT(*) FILTER (WHERE group_id = 4) AS \"04 - Credential Management\",\r\n    COUNT(*) FILTER (WHERE group_id = 5) AS \"05 - Dome Marketplace\",\r\n    COUNT(*) FILTER (WHERE group_id = 29) AS \"06 - Chatbot\",\r\n    COUNT(*) FILTER (WHERE group_id = 17) AS \"07 - Dome Search\",\r\n    COUNT(*) FILTER (WHERE group_id = 8) AS \"08 - Billing & Invoicing\",\r\n    COUNT(*) FILTER (WHERE group_id = 9) AS \"09 - Payment System\",\r\n    COUNT(*) FILTER (WHERE group_id = 3) AS \"10 - Offering Qualification Process\",\r\n    COUNT(*) FILTER (WHERE group_id = 7) AS \"11 - Integration and Replica\",\r\n    COUNT(*) FILTER (WHERE group_id = 12) AS \"12 - Infrastructure\",\r\n    COUNT(*) FILTER (WHERE group_id = 6) AS \"13 - DevOps Deployments\",       \r\n    COUNT(*) FILTER (WHERE group_id = 10) AS \"14 - Customer Care\"\r\nFROM \r\n    intervals\r\nLEFT JOIN \r\n    tickets \r\nON \r\n    tickets.created_at >= intervals.week_start\r\n    AND tickets.created_at < intervals.week_start + INTERVAL '7 days'\r\nGROUP BY \r\n    intervals.week_start\r\nORDER BY \r\n    intervals.week_start ASC;"
    }
   ]
  },
  {
   "title": "CLOSED TICKETS TREND",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 19, "x": 0, "y": 86 },
   "targets": [
    {
     "rawSql": "WITH intervals AS (\r\n    SELECT \r\n        generate_series(\r\n            DATE_TRUNC('week', NOW()), \r\n            DATE_TRUNC('week', NOW()) - INTERVAL '180 days', \r\n            '-7 days'\r\n        ) AS week_start\r\n)\r\nSELECT \r\n    intervals.week_start,\r\n    COUNT(*) FILTER (WHERE group_id = 18) AS \"01 - Marketing Activities\",\r\n    COUNT(*) FILTER (WHERE group_id = 27) AS \"02 - Project Website\",\r\n    COUNT(*) FILTER (WHERE group_id = 11) AS \"03 - Privacy & Legal\",\r\n    COUNT(*) FILTER (WHERE group_id = 4) AS \"04 - Credential Management\",\r\n    COUNT(*) FILTER (WHERE group_id = 5) AS \"05 - Dome Marketplace\",\r\n    COUNT(*) FILTER (WHERE group_id = 29) AS \"06 - Chatbot\",\r\n    COUNT(*) FILTER (WHERE group_id = 17) AS \"07 - Dome Search\",\r\n    COUNT(*) FILTER (WHERE group_id = 8) AS \"08 - Billing & Invoicing\",\r\n    COUNT(*) FILTER (WHERE group_id = 9) AS \"09 - Payment System\",\r\n    COUNT(*) FILTER (WHERE group_id = 3) AS \"10 - Offering Qualification Process\",\r\n    COUNT(*) FILTER (WHERE group_id = 7) AS \"11 - Integration and Replica\",\r\n    COUNT(*) FILTER (WHERE group_id = 12) AS \"12 - Infrastructure\",\r\n    COUNT(*) FILTER (WHERE group_id = 6) AS \"13 - DevOps Deployments\",       \r\n    COUNT(*) FILTER (WHERE group_id = 10) AS \"14 - Customer Care\"\r\nFROM \r\n    intervals\r\nLEFT JOIN \r\n    tickets \r\nON \r\n    tickets.last_close_at >= intervals.week_start\r\n    AND tickets.last_close_at < intervals.week_start + INTERVAL '7 days'\r\nGROUP BY \r\n    intervals.week_start\r\nORDER BY \r\n    intervals.week_start ASC;"
    }
   ]
  }
 ]
}