apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: zammad
    repo: https://zammad.github.io/zammad-helm
    version: 12.1.0
    releaseName: zammad
    namespace: zammad
    valuesFile: values.yaml
    skipTests: true

patches:
  - target:
      group: batch
      version: v1
      kind: Job
      name: ".*-init-.*"
    patch: |-
      - op: replace
        path: /metadata/name
        value: zammad-init
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/hook: Sync
          argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
      - op: remove
        path: /spec/ttlSecondsAfterFinished