---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: caddy-forward-auth
  namespace: caddy-proxy
spec:
  encryptedData:
    PROXY_PASSWORD: AgAjC6HHJYlMsJJPVUYmfWZ+yMk2/ux0Q70xhh1IzjWfCdx4R+CKPrUGcnIeWcZawkJMPpqOPbwxMO31VYS7D/BLxFCSkO0dl/4Z2mZKI501qrnlLFbHw9Qr63uOpUApc6XVMD0xSATxbF3ibhYV7C1EsDVralkCRBz/FZwroiypUG/F67WETxxYZi3mVvLe9wPgMPZaFiv+E3mIRD7xy+BcBbXPQstUr4BL5uT618jvbQyzIiPp3lC5fl2zZRTyqZcX/wyqgAX078ukKyoqSLXOLmc+Ppfwr9vP44MXtb5RHy6sKLoWyPJTv9whnDgMk+xJkOr3nK5r6sCfUU+GZ+baKtSASoXzEbu5ygB4vvfHJzipPIvRt190hQ/ZHbyKaycrZh+hGOZXrBMQTs8kcn5F6t3AhpR4YbJNzU7K1GdO5bFh03stndS4oDnnYcWHW+TB/gQQC0lIIz/w91yzRJh3KXwRklTDDn5ggUb90j/lrhPL+UtG7YIksoTIEWikKCUCOTWXnSl9BrMhTKX5WHrQJ0P7iHezszZovlrOppyMMUjvAXULzdV3PG5DX1qYyb0D1JKj2CKWYk+QdUyVbBHQBSWs9AvWe5sq4xxq4NHqbyK2MfMXrgv0hulZ6U0V+OiNFSuGUGiIPPSPy7VcEGfUGDWzBMES/6vpjCX+pX07JpzD37e22Ya09riGHEjt9BoZ4w4bnPy3H3Tm3ejz6yGNAYJssqj2RkOIWJqT0zT3TO6O4vtCYDN2FOnhJI2YjQg=
    PROXY_USERNAME: AgDDxPkzpFYiGJ2OTd3dr+EelCXEuM5YN3QaW9MIlcbFyFYg08XuaPQsmEZkepMoKasPf+oWJf8zbt0rS9SjazUjWWib5+ocGH9YsYg0NP/wA+gy2GTjhQXISYXhn2eBysxNFEYUYZMCJwvpZJcoLQQKEf0drz3/jyVq51liKtDffwCPFyNXElOz09vO3R3706QDYTPTv3rhY/7/93a2UiFa8O0BMCNPQ+Ga5iCdzFE67F9C3K0bfxljE4wSFCLXQZLVJzZNCzWWrygILd/4h4ffwxQDPc0mKNU3tE37bhBLsIoPpOQL+k1VvKPUPK58qEVMA8LGU+UJ6zEmlM/FEIEZlia2YPH0PoAgaVw+A9FT4jEv6Wl2ubo6N1qtn8ihjOsZ+e5cIgnsgZnk2j+SqX1Tq0YxL2MTgrALXQRVQi2Qa+rcdj1S64OYdk+Fl3RPfZeVzMkKVfNDBFh51hVPlTqG+cUSZh2eIHHAfzoc+XGJ3meuQK7riWxHB0Vr/By004JvNV430SPm+7iJeulAHK08fMS1QwEAuNKpC+BHv1Q2Ys/qz6oYHIOipLKVyohAxAEldpmwdx0Ai2U7RRReWrTi7ydxquMrF9U2vhEVvT5IKDq8G5T1HUjDQjZbIOsm1svsBcxxg+7dHF1TzbpAxYlS5GCJwJmixppft19i7riNqWaHkcRxuN6xZMuhAZbDbmTPNSfgkIkYWw/Q0g==
  template:
    metadata:
      creationTimestamp: null
      name: caddy-forward-auth
      namespace: caddy-proxy
