apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: caddy-proxy
spec:
  encryptedData:
    .dockerconfigjson: AgArCndnDgYEcAdko35YI+H1KUpiIARxLaQSvX4LB2NHVmw4GqkpQYPNatP0MD7ogV7Cg2w8skS/FXHU+LfM9FvY5Kq/FRm/D3M1CoPQZsARG5/ixjtatpZePN7pNKKA2fnBEbH9ewgRyhENXAP15zsOk8nLNs+yN5YasUyBSWexTec15QDNn1UZtMQVPDyHOGA/+moOoGirYDjS/lCJNdrPEY5xVH1A2NfPdU4/Pt5RpkuGVixeavfKF9zzIvUNuu0OEObHWBtjD28cZjYnb8KsH7RbIjvwdsgE4x2bcvjqq9+fUGED0yfrubgiw9CIqULJjoQTSNYO53h3SilKssYXmfQhQBDPKHyQ7AWgMcFqoi2ArVyDwGH2Wdyt/NsdPA5o9WSdh9GzsXro1k/35xA/4e/1k7v4rb55OUGGXvMmIS3nUTsn8eUGRav7l4zCg7uzZ7HCatYFUxkyHbUzgOZTQof06XNLK8KxNoK9GUiBdT+gtH5NvCJqXEq0zyrk6Yj1FIfkW72c4TokZW5ybXuDFJhs6TbPwv6Ke4YJ0hYgiLHS/aCBKBt1m88L/fDGorSvc+djQGs8Z1g5taMcq5G1v2Dk8tiTIKKr+6RbNwpUaIleiGbn20xuGoF6vtsdRjzHbMGN8gUMyjgwWQCYFY2bSPZ/0BiTLMWM0KW85im6fUVrUOUy2Y2itOCAmm8rfINj6iTf1dsxkahX8NS75V6lu7vgu3bQGGWTHLbZ1zd7Rk/cGRho9vAMtCr0Nr3mdkUvvox279cZL5x4SDsElkP//GTllYeXc0pVbAMElDpCLXxTrB5BEVxo6+WaBkvdUEBek1rMXUyYfNhr/Q7x+hNJMdR34dC4GbI5J/mNdZTn47y/6GUn/GHHWqxTuqed3azF7V2xpoFK1EOs74b/QEYCPG0QTjH/6PISfKzFqLzDuBxBS5SUJ8BS+kX2r8BXdCpc+w==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: caddy-proxy
    type: kubernetes.io/dockerconfigjson