apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - forward-auth-sealed.yaml         # il SealedSecret (§4)
configMapGenerator:
  - name: caddy-proxy-config
    files:
      - Caddyfile=Caddyfile