apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-module
  namespace: analytics
  labels:
    app.kubernetes.io/instance: backend-module
    app.kubernetes.io/name: backend-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: backend-module
      app.kubernetes.io/name: backend-module
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: backend-module
        app.kubernetes.io/name: backend-module
    spec:
      containers:
        - name: backend-module
          image: docker.ramp.eu/ed-pvt/dome-matomo-backend-app@sha256:6d1cba80b9e98863c76f342b4d3f9f169c387a3770108767f4d109b1fb4bf3e7
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
