---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: private-key-verifier
  namespace: billing
spec:
  encryptedData:
    PRIVATE_KEY_BASE64: AgBysODzesmrsYNBH7A7XqGcb2QJ/8hwmOCkw3B404XMutkut2XOs1PjfqMp3H+S+N5JcuWe0y21i5QOHfAbznoh7IUmSw6xcj3iBK/uVK7S9SnXnecbuLUQI9p5G/AgelQMU+JkDPUZbCKdfyFlqrpdHDk1G1akCUSvWXMgOsxtlY3mU/q0EK9lRd+DxIxYAgOqiS9bdo/G5DKr6sysqpdSMt4NZGw9jtdMssMYNnrBKGpzg5Lgr9PhKZ45jKPEsU8Mka1ZAHg94u/AjkSe59FhfSh5N5241OQBmUGyaMeuNFFTvDypoYrBoH4canaYL/p6fwIhjBVNfXZRzScTNW2fWbKr8xassGcn8yz0Qj+eSAOKaDD4xaZtEw+G4kTwF2AFdiCTHCPcD+Lndmih6pd9VnKhGdkFvkfaG12HbTYuZL5UnhCoo4VMMGGrrP7bh1lXczcO+u9a2Lh0ivmg13eGZYzfxFukJgd+5opMRnHg9M1fRXXCG1V2DzYTLCN+8c7RCZbIYB+GFWekS/GiEx7EFAIdCGleFn0sP+/HCic9ZPA9lJkL0nx3eaGT9uUFOunUWvgiJ11f8cSt0ZtGLOotGxbKkV0h5zA/wdVlqO2fRVafVrHyb2//gXlt6lxTfLpP8yzOUZI9XfVOYQEte8/jcwoCoc/aJyEdCmDcZUdTVsOitzmDDq//C4++QHVy75t/SJ1l1TmDXV4GO5C2mmR2r1YLh3ITZZ7gHw7SBM7JMWE60nQegH0k0rcMIA==
  template:
    metadata:
      creationTimestamp: null
      name: private-key-verifier
      namespace: billing
