credentials-config-service:

  # Image
  deployment:
    image:
      repository: quay.io/fiware/credentials-config-service
      tag: 1.0.1

  # Resources
  resources:
    requests:
      cpu: "50m"
      memory: "384Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  # Database config
  database:
    host: mysql-til
    name: ccs
    username: root

    existingSecret:
      enabled: true
      name:  mysql-secret
      key: mysql-root-password
