---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mail-relay-zammad-secret
  namespace: zammad
spec:
  encryptedData:
    password: AgAJsSQDpyKyOtmPg1PBnvQSKLBPjybzrZNd6ja/dlUTOFuMBb76pa2PvoF3QmtApAoapmS5HCXaNvVpc3d7ZfYTfezn2D2p+3LAKiC/iskHJoYBEozeat2VNyYH54wn0fO1GlB5LTszokZhP/X98s/5lv5i53J+SQUHyDQGE4sJdQKyqmkAoSNh8sXpOln+XshZN3M7i7SlcrE+/pep5ddEVEIvLSI2calRwDq3c9m4xQKeBaK5sfR04jtv0bZxyfpX6yFUZ1migYj46Q16NwwVRTSzWQ7SDDlsaOMco7cc30StqyEyuk0V3wxyWnUW5C+Jm7eEnQW4lNZoa/7j3tfLROBDDbu+TvSSw1IjPpoe5dSx+eCu/Po5b8USLZ1u4NmZwPR1DdvJcWGToT9gPUUb/4brJBP4VcF9OZJgBZtG1/XIrur4Fo7pUyeHcw5wFt3PjXVRypZI3rv0kUsKTJRHhsrbpz7cxzYnx+yK2bMEa2y0LIRA/K1d2KRZu6uSsiPWz148VvqpZLr4XIZj844Cnz2OT3uxj8uccm16u7jX0mW3YonG8LheCGycY0vl4hPOOtkPV9URh3ASfaGVfyr4jSMZ4OM3/mPxr/8y9/+FXL8Rk7GE9/lYVpcOyIDpF0mYEnXTzs9PNEjsUX4cJUN66uF6IFr3hYHPKKBb4fLgNb3ZZM9GgLnK3Sd3ADKBsr9b45OHpRQaFfM=
    username: AgAPFKrB1ykJ+VETuwr1ZNGlIlrG9u8VTaXi7qxhIIxdMSkvc3AUiNB6c0XujJBCxJCvnY2NF/Z5loB+zj55KqtjGxelh/SmYk8pipd/1bgU3LahjoCK17Kok1cdke1eyvVecu3UgeTxy9d8/NSY8m8wIN8PdYsQzZhWkKDuO4qjsvZmzFLql+h8xVIx51IS4HSmx5tal/ALmw74XVsS0Y2CU0Qje+B9pLDdjITgeUi4UzdNO6iPoj7OnOuFuNx2+q5OPONK+oS7hJsNH/95mtB5fBduBzqXcrUm59dKgXoNpS2HS0vHfxRIXbDdfOxSyDXDT/6o9TP9p9hAeM5f9KBwBLnnPZvZyxwDOcu6uhTyKuPvqQa7I+GittbEjPpRSx4E/kNrjtjAghRtq3Kv12C/v5LWyI0Y3zZwzmwY3chOj9nn+fdn5c0/krXli2k8bwSS6wJWowsBiCSk7+x+fh2LrDon/wCysn9ETEjL/UA1agd/bYzKb1eQ6dju1m8Pvp6lTft8zvez2V/Hc/7HBkG1JiIXA3xBlUqnNpxjXGyG8J1SP7LQaMoRw2u63keVrtYLaWrrKjU9Zolks4vro0948EXe4XMjyvhRXOazJu/nenIIuQwUz3e8w/u8fB9eCZL3MLM+TuWB43O+ff/+lznQ4Rxag6ZYV/+Xvo38ZiQvJ4W5n9Igc7b8aFGLomiA5GqmZHEnme3Unr5fcAav409hxVrRHKBNY/R597dNyUYZHWSJFfg=
  template:
    metadata:
      creationTimestamp: null
      name: mail-relay-zammad-secret
      namespace: zammad
