---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mail-relay-zammad-secret
  namespace: zammad
spec:
  encryptedData:
    password: AgBPeVoZNQon8t/HENAiTuOE8HVuiCY4H8A0w/A5AquQ3xQKEec/uAJoMbp8zQwjHbWcm9nGdbajmbhRzjHd2EONoZPCNQo+jrWNfY7tEP6aXqpSYeHe/dQoiBEJ8m0X41U01luwvVhET/4TQp8VKFiH0BzvmWmE5GKgVS6U1eg2NTJsGZQYg4F4TDG+UCvrP8oxKl/xV3MYBT3ODJn4qyOdW0JFZOM1kqTjLaIJG8/Fw67B/e5ExzZCWuwWgszx+Jp3xzzF5wZPLCbXVZ9qwdIGs0ZHNgZ+fVUUOlOa+kFlEkIlub1uVli2WRXta0MOd4pOVC8+aXwr2KNGW0CXJUJgi2qHMeIX7A9i1mfaBE1TL6d69fCzSOIvlXQhMyf5SqrbVOpxLu3selv5dWMUKOPVU+TNRQKAmaDSd97eUMcfVCJbRq1UBWiFs9UXG+Wpi9v98auPmuIfPiwFnmrIWa432Et/jQUXzCdAohOJwQIHjiiDyDDCJcHQhheZyab1H7ykNGu7oFX33ITD7LCkRe0ew8MP8T9kVvnFReZ6ujevdNpgzIuJJPoJX8E9JybYSZ0jnkMy+6OYHOmrTUlnkVlwqvR9Hj0M8yNWs+uOoo9O6FsqILINIXb1k1P9RWS8lvW7vNJSutme+vyyUEO7AZyseiMXukJXEymfKbKzNACwKaU8haO97jMCvMEuQuyR0HQG6Mh/H4oQcRw=
    username: AgBl7DFkRm7GahhZlkYRg8xXOGjE/JbW1iaVVRBiKrKBBiUXfvvq5OE0rfJJpYufg4Qa2V23E6sWRmZ3VrkquKrPW8vJtRIFelVPAjPs/RmlTQA7cfkuel+cuNKLp5Jeqy/uhmvGrBZlDWU9GC/AkZbQva4vnBkuNmTkim4nqMY/ngAFRCwSsejfeT/y9bQ03QAmRQklV8DIiPVERp5P4SD2rUMbZqnGA5HkZTL6lJwX2EXl6esPtf3v06jQE7emSrcdfwYtzeG+gd/+JseoLZNgZiOP+mb2n1ifFZKveHhXjOCpCjU3pKQXtnmiRxGte+BS6MgRZ1w9U09P3Ig6sVOf9MvITif8/94JtWnWrL9Jl9/9YzL3XpPvwANrQsCkNQeAP7Q2fjcJy7Y0mjJMxHbsVCWD2Ezq8lcHyfd8oM1uBaGHaXfjg+l1nTIx0TIwdlK8W0cCQ03Rp/b3EpCvkbcGYieIYzs0agm7bMv7oElAIEyq7VH2hdOXDKh1y7j1FHiuYM82aCxuMvk1mbwGt80JswyOg5WKYOWj3elQrz2v0mvAfpp0y1K/yQwBjLZ73F5mHpadggov03G1+gV4yn4qmTyfTZ1WRgyK3N4cllnOo2Vn971pHNAlhBOS/ION20yD5M/5tqFeagwSSK5+Gmd3z7Pg9JPdmxiXt//kbjaCPpB4vWtPnXazL/Bd/ZmCZZB08hsdgveqK9wMvj6mOGXxGUX/DOwCsLxcuIrD+M0NcQGfHkc=
  template:
    metadata:
      creationTimestamp: null
      name: mail-relay-zammad-secret
      namespace: zammad
